# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      -main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-actions@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DCOKER_PASSWORD}}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{secrets.DOCKER_USERNAME}}/app-name:latest
          docker push ${{sexrets.DOCKER_USERNAME}}//app-name:latest

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Kubectl
        uses: azure/setup-kubectl@v1
        with:
          kubeconfig: ${{secrets.KUBECONFIG}}

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/deployment-name container name=${{secrets.DOCKERHUB_USERNAME}}/app-name:latest
          kubectl rollout status deployment/deployment name

      

       
    
          
